### ISSUE TITLE
One question about Marlisa training.

### ISSUE THREAD

**Issue by HYDesmondLiu** [intelligent-environments-lab/CityLearn#19]
Thank you for sharing the repo. I have a question about reproducing Marlisa result.
In the paper, it says: 

`MARLISA performed constrained random action exploration
for the first 250 days of the simulation. Then, it performed an
exploration-exploitation process using SAC to maximize the
expected rewards and the entropy of the policy (for 300 more days).
Finally, after 550 days into the simulation, MARLISA started to
evaluate the stochastic policy deterministically (by choosing the
mean value of the policy rather than sampling from it).`

So, in order to reproduce Marlisa, I have to:
1. Set `'start_training': 6000` and `exploration_period:6000` (250 days * 24 hours), ` 'safe_exploration':False` since with True it is controlled by RBC
2. When timestep is 13200 (550th day), I should set `'is_evaluate' = True`, so that Marlisa gives a deterministic policy

Am I right?

**Comment by kingsleynweye** [comment]
@HYDesmondLiu yes, you are correct. Training and exploration start at time step = 6000. Safe exploration should only be set to True is you want to use the RBC during exploration. At 13200 is the correct time step to begin using the deterministic policy.

**Comment by nagyzoltan** [comment]
@HYDesmondLiu the MARLISA code does not use the centralized version.

**Comment by HYDesmondLiu** [comment]
@nagyzoltan 
Even with the decentralized version and followed all the descriptions in the paper. 
Still, it cannot get the cost lower to ~0.8 as the paper claimed. 
The best I can get is around 1.00

**Comment by nagyzoltan** [comment]
Thanks @HYDesmondLiu for letting us know. 

The issues could be slightly difference code bases as things have been developed since marlisa was first published, and perhaps not all hyperparameters are published. I remember in last year’s challenge we tried to avoid that participants would directly copy from the repo. This may have been an unintended effect. Also, there are several scores, some don’t go below 1.

We’ll need to check in detail when things around the challenge this year calm down. We’re a bit short staffed at the moment :)

**Comment by HYDesmondLiu** [comment]
Thank you @nagyzoltan for the detailed explanation.
It makes perfect sense and I am excited about the challenge. :)
