### ISSUE TITLE
[FEATURE REQUEST] Adding Vehicle batteries to the environment

### ISSUE THREAD

**Issue by tccf1109** [intelligent-environments-lab/CityLearn#48]
Dear all,

First of all, thank you for creating and maintaining such interesting open source OpenAI Gym environment for MARL as a way to standardize development in the area. I'm currently working on a V2G optimization multi-agent architecture and while doing the state-of-the-art research I've come to find CityLearn. As far as I understand a significant set of assets are already implemented for the OpenAI Gym, including stationary batteries. But I think it would be interesting to add vehicle batteries and their specific modelation.

For example, adding specificities such as State of Charge (SOC) on arrival, requested SOC of EV at departure, requested departure hour, typical arrival and departure date time, maximum EV charger efficiency, among others. I think the citylearn.energy_model.Battery already models a big part of the batteries and so I think adding V2G to the environment would be a very interesting step forward.

Are there any plans to implement such elements ?

Best Regards,
Tiago Fonseca

**Comment by nagyzoltan** [comment]
Hi Tiago (@tccf1109),

Thank you for kind words, we appreciate that CityLearn is useful to the community.

Indeed, your question/feature request is spot on. We’re very much interested in integrating EVs (and other energy systems) into CityLearn and it is in our roadmap. We’ve made CityLearn open source so the community can develop and integrate modules that it deems important/interesting and could benefit all; and because we’re too low on manpower to do everything we want :). We are also not experts for every possible system, for example EVs.

That being said, would you be interested in taking a stab at a first version for an EV module?

Happy to chat more, if you’re generally interested. We have been working on a major update in the background in collaboration with some major universities around the world, so we’re experienced integrating modules and ensuring quality control along the way.

Let us know what you think
Best, Zoltan

**Comment by calofonseca** [comment]
Hi @nagyzoltan, now I'm using my university account

I'm interested yes, because in the scope of my Master Thesis and research work (at the school of engineering of the polytechnic of Porto, Portugal) I plan to extend the CityLearn Environment for a V2G/Energy Community use case where I apply a multi-agent RL for energy scheduling. I'm also not an expert at EVs but I will certainly take a try at it, mainly starting next month (April).

I think it will be good to keep in touch, and most certainly talk along the way and if agreed we can schedule a online meeting, mainly next month when I will be out of state of the art research, and more involved in implementation/coding. 

Best regards,
Tiago Fonseca

**Comment by nagyzoltan** [comment]
Okay, sounds good @calofonseca . Keep us posted and we can most certainly meet along the way.
Best, Zoltan

**Comment by calofonseca** [comment]
Hello again @nagyzoltan 

As I previously my goal was to work on to develop the EV capabilities to citylearn. I've been working on that, and until the end of this month I think I will have a stable version. 

Maybe we can chat sometime in the near future to get to know better how can we integrate this module, since I have tried to follow along the way that you have idealized citylearn, however sometimes I'm not sure if you will like the way we did it. But we are more than happy to contribute and try to find the best way to do it

Please let me know if it is ok for you to chat sometime in the beginning of next month.

Best, Tiago

**Comment by nagyzoltan** [comment]
Great!! Can you email me (nagy@utexas.edu) and @kingsleynweye (nweye@utexas.edu) to setup a meeting next week?
Thanks, Zoltan

**Comment by nagyzoltan** [comment]
Closing this for now.
